### PR TITLE
Improve scalability of metadata reading with large n morphologies

### PR DESCRIPTION
**Pull request by Helveg**

### CODE REVIEW

**Comment by Helveg** [comment]
> This has indeed drastically improved the access and storing of metadata. The memory consumption is also much better. I have run a profiler to see where the program (in [dbbs-lab/bsb#716](https://github.com/dbbs-lab/bsb/issues/716)) spends most of its time (see attached reports).
> 
> Screenshot from 2023-06-01 11-22-21 Screenshot from 2023-06-01 11-23-58
> 
> It seems most of time is spent by json encoding and decoding the metadata. I am not sure we can compress this time... IMO, this is however satisfactory improvement.

The call count is 13465, why is this number so high? My new implementation should only load the metadata once per selector, which should run only once per job. So I'd expect a call count of 1. How many morphologies where in the repo when this profile was made? Or how long did it run?

**Comment by drodarie** [comment]
This high call count is related to the number of morphologies that are stored in the hdf5 file in the end. During placement, every morphology generated is individually saved with the function `save` in `morphology_repository.py`. This function loads all the metadata to update it. The json loads function is also called once in my own generate function for each placement job when I load the morphology (`load` in `morphology_repository.py`). 
I cannot tell you how many morphologies were stored in the h5 file during my test with the profiler (as I do not have the file anymore) but the total time spent on this program was ~12min.

**Comment by Helveg** [comment]
> During placement, every morphology generated is individually saved with the function save in morphology_repository.py. This function loads all the metadata to update it.

Ah ok, I see that I must have some unpushed code on my work desktop; I namely made sure that during the saving of N morphologies of a generated MorphologySet the metadata is also loaded just once.

At the moment I don't see this optimization in `bsb` so I must have it lying around somewhere. I'll submit it as a separate PR so we can revisit the profile again at that point :)

**Review by drodarie — CHANGES_REQUESTED** [review]
If [this suggestion](https://github.com/dbbs-lab/bsb-hdf5/pull/26/files#r1212910979) is implemented, you are good to go.

**Pull request merged**
